---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - update.norbinto
  resources:
  - safeevicts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.norbinto
  resources:
  - safeevicts/finalizers
  verbs:
  - update
- apiGroups:
  - update.norbinto
  resources:
  - safeevicts/status
  verbs:
  - get
  - patch
  - update
