# This rule is not used by the project node-updater itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the update.norbinto.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-updater
    app.kubernetes.io/managed-by: kustomize
  name: safeevict-editor-role
rules:
- apiGroups:
  - update.norbinto
  resources:
  - safeevicts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.norbinto
  resources:
  - safeevicts/status
  verbs:
  - get
